{{/*
include does not work well in range, work-a-round it with $dot variable
https://github.com/helm/helm/issues/3684
*/}}
{{- $dot := . }}
{{- if .Values.ingress.tls }}
{{- range .Values.ingress.tls }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .secretName }}
  namespace: default
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ index .hosts 0 }}
  dnsNames:
{{ toYaml .hosts | indent 4 }}
  acme:
    config:
      - dns01:
          provider: {{ .acme_provider }}
        domains:
{{ toYaml .hosts | indent 10 }}
{{- end }}
{{- end }}
