---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: admin-knightdark-3bagels-com-tls
  namespace: default
spec:
  secretName: admin-knightdark-3bagels-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: admin.knightdark.3bagels.com
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - admin.knightdark.3bagels.com
