{{/*
include does not work well in range, work-a-round it with $dot variable
https://github.com/helm/helm/issues/3684
*/}}
{{- $dot := . }}
{{- if .Values.cronjobs }}
{{- range .Values.cronjobs }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "service.fullname" $dot }}-cronjob-{{ .name }}"
  labels:
    app.kubernetes.io/name: {{ include "service.name" $dot }}
    helm.sh/chart: {{ include "service.chart" $dot }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" $dot }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          # specifies to local dns resolver to use tcp over udp, work-a-round for
          # such problem:
          # https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeoutspaste>
          dnsConfig:
            options:
              - name: use-vc
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          containers:
            - name: {{ $.Chart.Name }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              command:
{{ toYaml .command | indent 16 }}
              args:
{{ toYaml .args | indent 16 }}
              env:
{{ toYaml $.Values.env | indent 16 }}
              volumeMounts:
              {{- if $.Values.persistence }}
                - name: data
                  mountPath: {{ $.Values.persistence.mountPath }}
                  subPath: {{ $.Values.persistence.subPath }}
              {{ end }}
          volumes:
          {{- if $.Values.persistence }}
            - name: data
              persistentVolumeClaim:
                claimName: {{ $.Values.persistence.pvc }}
          {{ end }}
          resources:
{{ toYaml .resources | indent 12 }}
{{- end }}
{{- end }}
