{{- if .Values.deployment.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}
    helm.sh/chart: {{ include "service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
{{- with .Values.deployment.strategy }}
  strategy:
{{ toYaml . | indent 4 }}
{{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      # specifies to local dns resolver to use tcp over udp, work-a-round for
      # such problem:
      # https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeoutspaste>
      dnsConfig:
        options:
          - name: use-vc
      dnsPolicy: ClusterFirst
      initContainers:
        {{- if .Values.persistence }}
        - name: fix-data-dir-ownership
          image: alpine:3.9
          args:
            - sh
            - -c
            - |-
              chown -v 1000:1000 /mnt
          volumeMounts:
            - name: data
              mountPath: /mnt
              subPath: {{ .Values.persistence.subPath }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.image.args }}
          args:
{{ toYaml . | indent 12 }}
        {{- end }}
        {{- with .Values.env }}
          env:
{{ toYaml . | indent 12 }}
        {{- end }}
          {{-  if .Values.deployment.port }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
          volumeMounts:
          {{- if .Values.persistence }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
              subPath: {{ .Values.persistence.subPath }}
          {{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.securityContext }}
      securityContext:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      {{- if .Values.persistence }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvc }}
      {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
