{{- if .Values.HorizontalPodAutoscaler -}}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "service.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "service.fullname" . }}
  minReplicas: {{ .Values.HorizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.HorizontalPodAutoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.HorizontalPodAutoscaler.targetCPUUtilizationPercentage }}
{{- end }}
