{{- if .Values.VerticalPodAutoscaler -}}
---
apiVersion: autoscaling.k8s.io/v1beta1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "service.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updatePolicy:
    updateMode: "{{ .Values.VerticalPodAutoscaler.updateMode }}"
{{- end }}
